### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by xiaozhute** [xiaoboluo768/qianjinliangfang#1]
# 打开events_waits_current表的当前等待事件记录功能
mysql> UPDATE setup_consumers SET ENABLED ='NO' WHERE NAME ='events_waits_current';

# 这里打开不应该是YES么?   【performance_schema 配置详解】
mysql> UPDATE setup_consumers SET ENABLED ='YES' WHERE NAME ='events_waits_current';

另git上 5.-2，5-3等图显示不出

**Comment by xiaoboluo768** [comment]
* 关于setup_consumers表的打开语句错误，已修订，谢谢！
* 另外，关于图片显示的问题，我这边显示是正常的，如果你那无法显示，可以从如下地址中找到对应的图片，并进行下载：https://github.com/xiaoboluo768/qianjinliangfang/tree/master/image
