### ISSUE TITLE
【附录 B show engine innodb status 详解】 【TRANSACTIONS】第二行有错别字

### ISSUE THREAD

**Issue by huangluyu** [xiaoboluo768/qianjinliangfang#2]
https://github.com/xiaoboluo768/qianjinliangfang/wiki/TRANSACTIONS

``` 如果在这里看到了锁等待细细 ```

**Comment by xiaoboluo768** [comment]
已将 "如果在这里看到了锁等待细细" 修订为 "如果在这里看到了锁等待信息"，谢谢你的支持！
